include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v1
    file: '/.gitlab-ci-template.yml'

variables:
  SERVICE_PORT: 80

build-review:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    DOCKER_BUILD_ARG_REACT_APP_MAPBOX_API_ACCESS_TOKEN: '$MAPBOX_API_ACCESS_TOKEN'
  only:
    refs:
      - external_pull_requests

build-staging:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
    DOCKER_BUILD_ARG_REACT_APP_MAPBOX_API_ACCESS_TOKEN: '$MAPBOX_API_ACCESS_TOKEN'
  only:
    refs:
      - develop

build-production:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
    DOCKER_BUILD_ARG_REACT_APP_MAPBOX_API_ACCESS_TOKEN: '$MAPBOX_API_ACCESS_TOKEN'
  only:
    refs:
      - master

review:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    POSTGRES_ENABLED: 0

staging:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
    POSTGRES_ENABLED: 0
  only:
    refs:
      - develop
