dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - yarn install

script:
  - yarn lint
  - yarn test:ci

after_success:
  - codecov < coverage/lcov.info
