version: '3.7'

services:
  app:
    container_name: ahti-ui-new
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
      dockerfile: docker/ahti-ui-new
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
  env_file:
    - .env
