# This file configures the headers and redirect rules for Netlify.
# Some are important for the page to work correctly, and other
# are for performance.
# Reference: https://www.netlify.com/docs/netlify-toml-reference/


# Redirects
# NOTE: These match top-to-bottom, so more specific paths
# should come before more generic ones
# Reference: https://www.netlify.com/docs/redirects/#splats

# Place any specific redirects here

# Anything else, we redirect to index.html
# This is required for the client Single Page Application to
# pick up the routes by itself.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
# NOTE: Same here, matching top-to-bottom

[[headers]]
  # Anything under /static is hashed by CRA, so we can cache indefinitely
  # Reference: https://facebook.github.io/create-react-app/docs/production-build#static-file-caching
  for = "/static/*"

  [headers.values]
    # Multi-key header rules are expressed with multi-line strings.
    cache-control = '''
    public,
    max-age=31536000,
    immutable'''

[[headers]]
  # Assets under images/ are mutable, but large
  # We cache them for a small time, to avoid excessive data consumption
  for = "/images/*"

  [headers.values]
    cache-control =  '''
    public,
    max-age=600,
    must-revalidate'''
